version: '3.8'

services:
  db:
    image: postgres:15
    container_name: metabase_db
    restart: always
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase_postgres
      POSTGRES_PASSWORD: metabase_password
    volumes:
      - db_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:v0.55.8.x
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_postgres
      MB_DB_PASS: metabase_password
      MB_DB_HOST: db
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

volumes:
  db_data: